<?php
$rs = array(
'index' => '首页',
'relogin' => '重登录',
'hide' => '隐身',
'controlpanel' => '用户控制面板',
'loginout' => '退出',
'manage' => '进入管理模式',
'guest' => '游客',
'login' => '登录',
'reg' => '注册',
'value7' => '论坛暂时关闭',
'user_login' => '用户登录',
'user_name' => '用户名：',
'user_pass' => '密　码：',
'validate' => '验证码：',
'cookie_seting' => 'Cookie 有效期',
'cookie_now' => '即时',
'cookie_hour' => '一小时',
'cookie_day' => '一天',
'cookie_week' => '一星期',
'cookie_moon' => '一个月',
'cookie_year' => '一年',
'Sumbit' => '确 定',
'Reset' => '清 除',
'value21' => '',
'value22' => '',
'value23' => '',
'value24' => '',
'value25' => '',
'value26' => '',
'value27' => '',
'value28' => '',
'value29' => '',
'value30' => '',
);
?>