<?php
$rs = array(
'index' => '首页',
'relogin' => '重登录',
'hide' => '隐身',
'controlpanel' => '用户控制面板',
'loginout' => '退出',
'manage' => '进入管理模式',
'guest' => '游客',
'login' => '登录',
'reg' => '注册',
'value7' => '论坛暂时关闭',
'nologin' => '你还没有登陆！',
'error_pass' => '密码错误！',
'error_null_pass' => '密码不能为空！',
'error_null_newpass' => '新密码不能为空！',

'checklogin_error' => '用户名或者密码或者验证码没有填写！',
'ajax_login' => '点击这里进行快速登录',

'user_login' => '用户登录',
'user_name' => '用户名：',
'user_pass' => '密　码：',
'validate' => '验证码：',
'cookie_seting' => 'Cookie 有效期',
'cookie_now' => '即时',
'cookie_hour' => '一小时',
'cookie_day' => '一天',
'cookie_week' => '一星期',
'cookie_moon' => '一个月',
'cookie_year' => '一年',
'Sumbit' => '确 定',
'Reset' => '清 除',

'tip' => '贴 子',
'title' => '主 题',
'r_revertime' => '最后更新',
'r_view' => '查看',
'r_revert' => '回复',
'revert_author' => '作 者',
'forummanage' => '论坛版主:',

'myname' => '用户头衔：',
'birthday' => '用户生日：',
'ucname' => '用户等级：',
'fortune' => '用户财富：',
'experience' => '用户经验：',
'charm' => '用户魅力：',
'integral' => '用户积分：',
'money' => '用户金币：',
'elitenum' => '精华帖数：',
'postnum' => '帖数总数：',
'regtime' => '注册时间：',
'vistitime' => '登录次数：',

'user_control' => '我的控制面板',
'user_changeinfo' => '资料修改',
'user_changepass' => '密码修改',

'user_sex' => '性    别：请选择您的性别',
'user_man' => '男',
'user_woman' => '女',
'keep_secret' => '保密',
'user_pic' => '头    像：',
'user_pic_explain' => '选择一个个性图片，当你发表时将显示在您的名字下方。',
'select_pic' => '(选择BBS中的头像)',
'web_pic' => '(网络头像 http://...)',
'user_sign' => '签    名：',
'date_exp' => '(1900－01－01)',

'old_password' => '旧密码确认：',
'password_explain' => '如要修改请输入旧密码进入确认',
'new_password' => '新密码确认：',
'password_question' => '密码问题：',
'password_answer' => '问题答案：',
'answer_explain' => '请认真填写以便您日后取回密码
答案采用了加密，只供取回密码使用，如要修改可直接填写。 
(不做修改请留空)    ',

);
?>